using System;

namespace ColorMatcher.Models
{
    /// <summary>
    /// Represents a single color matching attempt in project history.
    /// 
    /// Each ColorHistoryEntry captures a snapshot of the color matching process at a specific moment,
    /// including the reference and sample colors, calculated color difference (DeltaE), and the recommendation
    /// provided by the matching algorithm. Entries are collected over time to create an audit trail of matching attempts.
    /// </summary>
    /// <remarks>
    /// Entry Lifecycle:
    /// 1. Created when user saves a color match (SaveColorMatchAsync in ViewModel)
    /// 2. Populated with reference color, sample color, DeltaE, and recommendation
    /// 3. Optionally marked as accepted or rejected by user
    /// 4. User can add notes describing the attempt
    /// 5. Persisted in project's ColorHistory list to JSON file
    /// 6. Can be reused - user can apply previous sample/reference colors to new attempts
    /// 
    /// DeltaE Interpretation:
    /// - Less than 1: Match imperceptible to human eye
    /// - 1-2: Just barely perceptible difference
    /// - 2-5: Noticeable but acceptable difference
    /// - 5-10: Significant difference, likely unacceptable
    /// - Greater than 10: Very obvious mismatch
    /// </remarks>
    public class ColorHistoryEntry
    {
        /// <summary>
        /// Unique identifier for this history entry (GUID).
        /// Auto-generated on creation for tracking purposes.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Reference color (target color) at time of this entry.
        /// Typically the color being matched against. May be null in rare cases.
        /// </summary>
        public RgbColor? ReferenceColor { get; set; }

        /// <summary>
        /// Sample color (candidate color) being evaluated.
        /// The color being tested for match against reference. May be null if sensor reading failed.
        /// </summary>
        public RgbColor? SampleColor { get; set; }

        /// <summary>
        /// Delta E (color difference) between reference and sample.
        /// Calculated as Euclidean distance in LAB color space.
        /// Ranges from 0 (perfect match) to ~100+ (completely different).
        /// </summary>
        /// <remarks>
        /// Formula: DeltaE = sqrt((DeltaL*)^2 + (Delta a*)^2 + (Delta b*)^2)
        /// Represents perceptual color difference to human observer.
        /// </remarks>
        public double DeltaE { get; set; }

        /// <summary>
        /// Tint recommendation generated by matching algorithm.
        /// Suggests direction to shift color (Red/Green/Yellow/Blue).
        /// Examples: "Shift more towards red", "Shift more towards yellow"
        /// </summary>
        public string? TintRecommendation { get; set; }

        /// <summary>
        /// Whether this match was marked as acceptable by user.
        /// User explicitly marks entries they are satisfied with.
        /// </summary>
        public bool IsAccepted { get; set; }

        /// <summary>
        /// Timestamp when this entry was created (UTC).
        /// Auto-generated in constructor. Used for sorting history chronologically.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Optional user notes about this match attempt.
        /// User can document observations, conditions, or challenges.
        /// </summary>
        public string? Notes { get; set; }

        /// <summary>
        /// Default constructor. Auto-generates ID and timestamp.
        /// </summary>
        public ColorHistoryEntry()
        {
            Id = Guid.NewGuid().ToString();
            CreatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Convenience constructor with main color data.
        /// </summary>
        /// <param name="referenceColor">Reference (target) color</param>
        /// <param name="sampleColor">Sample (candidate) color being evaluated</param>
        /// <param name="deltaE">Calculated color difference (DeltaE)</param>
        /// <param name="tintRecommendation">Algorithm recommendation for adjustment</param>
        public ColorHistoryEntry(RgbColor referenceColor, RgbColor sampleColor, double deltaE, string tintRecommendation)
            : this()
        {
            ReferenceColor = referenceColor;
            SampleColor = sampleColor;
            DeltaE = deltaE;
            TintRecommendation = tintRecommendation;
        }
    }
}
